### ISSUE TITLE
Make grafana-dashboards.yaml configurable

### ISSUE THREAD

**Issue by brunobat** [grafana/docker-otel-lgtm#117]
We have this issue in Quarkus to create dashboards for our metrics and we were unable to place our dashboards without a hack.
Issue: https://github.com/quarkusio/quarkus/pull/41264

It would be nice if you placed in the `grafana.ini` the location of `grafana-dashboards.yaml` at `/otel-lgtm`, this way we could override the dashboards at our convenience.

The current location is version dependent, under `./grafana-v<grafana-version>/conf/provisioning/dashboards/grafana-dashboards.yaml`

**Comment by zeitlinger** [comment]
what if we just remove the version from the path?

I currently don't have a `grafana.ini` and would like to keep it that way if possible

**Comment by brunobat** [comment]
Removing the version from the path would also work, thanks.

**Comment by zeitlinger** [comment]
it seems this is already the case:

```bash
sh-5.1# pwd
/otel-lgtm/grafana/conf/provisioning/dashboards
sh-5.1# cat grafana-dashboards.yaml 
apiVersion: 1

providers:
  - name: 'RED Metrics (classic histogram)'
    type: file
    options:
      path: /otel-lgtm/grafana-dashboard-red-metrics-classic.json
      foldersFromFilesStructure: false
  - name: 'RED Metrics (exponential/native histogram)'
    type: file
    options:
      path: /otel-lgtm/grafana-dashboard-red-metrics-native.json
      foldersFromFilesStructure: false
  - name: 'JVM Metrics'
    type: file
    options:
      path: /otel-lgtm/grafana-dashboard-jvm-metrics.json
      foldersFromFilesStructure: false
```

**Comment by brunobat** [comment]
Thanks @zeitlinger. We will update the extension to use the latest.
