### ISSUE TITLE
loki log is display without the severity

### ISSUE THREAD

**Issue by vincenzopalazzo** [grafana/docker-otel-lgtm#121]
I do not think this is a good place to make this question but IDK where to make one of this.

So I am running the following libraries https://github.com/vincenzopalazzo/cln-opentelemetry/blob/main/opentelemetry-common/Cargo.toml#L7 

However with the recent version of the `docker-otel-lgtm` I see the log in the following way 

![Image](https://github.com/user-attachments/assets/bc312a54-2399-45a1-99c0-f34481445d7a)

But the the may version I see the log line displayed with the colors 

![Image](https://github.com/user-attachments/assets/5953f86c-6c91-4d47-89dc-9dd3209e737d)

**Comment by zeitlinger** [comment]
I don't understand this: "But the the may version I see the log line displayed with the colors"

Can you describe what changed or what you expect to be different?

**Comment by vincenzopalazzo** [comment]
Sorry if I was not able to make it clear @zeitlinger 

If you see the image first image, the log line at the info level is gray, but in the second image the log line at the info level is green.

I am not able to understand what it is changed across the two grafana instance in order to restore the colors

Do you have any idea?

**Comment by vincenzopalazzo** [comment]
Ah looks like the fields inside the log message are different.

With the docke image I have the `detected_log_level`

![Image](https://github.com/user-attachments/assets/bc312a54-2399-45a1-99c0-f34481445d7a)

But with with the docker image from may (or so) I get the field like `level`

![Image](https://github.com/user-attachments/assets/bbb62396-2b8c-42df-b4f0-e07fb289898f)

**Comment by zeitlinger** [comment]
we've switched to the native otlp endpoint: https://grafana.com/docs/loki/latest/send-data/otel/native_otlp_vs_loki_exporter/

**Comment by vincenzopalazzo** [comment]
So if I am understanding correctly there is no way to restore the colors? @zeitlinger 

Thanks for your time

**Comment by zeitlinger** [comment]
https://github.com/grafana/loki/issues is the right place to ask - but I've also asked internally

**Comment by zeitlinger** [comment]
will be fixed with the next grafana release 

https://github.com/grafana/grafana/pull/93574

**Comment by zeitlinger** [comment]
fixed with https://github.com/grafana/docker-otel-lgtm/releases/tag/v0.7.8

**Comment by vincenzopalazzo** [comment]
Thanks @zeitlinger

**Comment by arukiidou** [comment]
- relates #142
