### ISSUE TITLE
Feature Request: Add Grafana OnCall to this repository

### ISSUE THREAD

**Issue by mamiu** [grafana/docker-otel-lgtm#129]
Are there any plans to support [Grafana OnCall](https://github.com/grafana/oncall) in the `docker-otel-lgtm` stack?

If not, how hard would it be to add it?

**Comment by zeitlinger** [comment]
This docker image is primarily meant for demo purposes for OTel, so there is no plan atm.

If you find a way to configure a demo Grafana OnCall, a PR would be welcome - I'm not sure if this is possible however.

**Comment by mamiu** [comment]
Thanks for the quick feedback @zeitlinger.

I'll try it and if I can get it to work, I'll open a PR.
