### ISSUE TITLE
Use Tempo 2.6.1

### ISSUE THREAD

**Issue by eddumelendez** [grafana/docker-otel-lgtm#135]
Last two versions use a Tempo version with [this issue](https://github.com/grafana/tempo/issues/4121) and it was fixed in 2.6.1, see https://github.com/grafana/tempo/releases/tag/v2.6.1

**Comment by eddumelendez** [comment]
Sorry, I just saw the [PR](https://github.com/grafana/docker-otel-lgtm/pull/130) that has not been merged yet. Feel free to close it.

**Comment by zeitlinger** [comment]
pr is merged
