### ISSUE TITLE
Add docker compose pull

### ISSUE THREAD

**Issue by TomKeur** [grafana/docker-otel-lgtm#140]
Maybe it's an idea to add `docker pull` before `docker run`

**Current:**
https://github.com/grafana/docker-otel-lgtm/blob/main/run-lgtm.sh#L5-L16

**Suggested:**
```bash
docker compose pull  docker.io/grafana/otel-lgtm:${RELEASE}
```

**Why?**
Since I have not run this project for a very long time, it started an really old version. After I manually did: `docker pull  docker.io/grafana/otel-lgtm` I'm getting the latest version (which supports ARM 🎉).

**Comment by zeitlinger** [comment]
good idea - pr is welcome 😄

**Comment by prasad89** [comment]
@zeitlinger Can I work on this?

**Comment by zeitlinger** [comment]
> @zeitlinger Can I work on this?

Yes

**Comment by prasad89** [comment]
@zeitlinger thanks for confirmation!
Here is PR https://github.com/grafana/docker-otel-lgtm/pull/194
