### ISSUE TITLE
Mimir instead of Prometheus

### ISSUE THREAD

**Issue by jangaraj** [grafana/docker-otel-lgtm#27]
It is LGTM stack, so I think Mimir should be used, not Prometheus. Is there any reason why Prometheus was used?

**Comment by tyoc213** [comment]
Shouldn't then be called `LGTPro`?

**Comment by david-guenault** [comment]
So don't call this lgtm :-)

**Comment by aos** [comment]
One place where having Mimir here instead of Prometheus is multitenancy (with `X-Scope-OrgID`). I wanted to test if this is possible, how to get it working, but can't when Prometheus is used as a backend :-)
