### ISSUE TITLE
docs: adds some information about persistant data

### ISSUE THREAD

**Issue by vincenzopalazzo** [grafana/docker-otel-lgtm#34]
I noted that the docker is not persistent so with every restart the data are wiped.

it is possible to add some information to keep the data stored in the host disk?

**Comment by zeitlinger** [comment]
I actually like the fact that you always start from a clean state.

I guess we could create an alternative persistent docker image. @fstab wdyt?

**Comment by zeitlinger** [comment]
The docker image was actually meant to play around - not for production use.

How do you use it?

**Comment by vincenzopalazzo** [comment]
>The docker image was actually meant to play around - not for production use.

I was looking for an easy-to-use docker image to collect logs with open telemetry and due that I am not a docker person, this was really hard. I think your docker is really useful for people that want to collect logs or traces with this tech stack

**Comment by zeitlinger** [comment]
great feedback - I have to discuss this internally to see what our recommended solution for your use case is.

**Comment by zeitlinger** [comment]
Confirmed

- we don't want to support this docker image as a production monitoring backend. We have way too little resources for maintaining it as an on-prem solution.
- Not persisting the data is actually good, so users don't start using it in production :smile: 

If you're looking for a particular piece only, such as Loki, you can use the respective images, e.g. https://hub.docker.com/r/grafana/loki
