### ISSUE TITLE
Evaluate adding a dotnet example folder/container

### ISSUE THREAD

**Issue by macel94** [grafana/docker-otel-lgtm#51]
Would you be open to pr?

Could you describe what is the rolldice expected I/O?

**Comment by zeitlinger** [comment]
yes, that would be great

it's basically https://opentelemetry.io/docs/languages/net/getting-started/

**Comment by macel94** [comment]
i started working on it here, if you want you can assign this issue to me: https://github.com/macel94/docker-otel-lgtm
what do you expect to see in grafana, ideally?

i have made something work before but it's a lot more code and still not finished(doing it in my free time as always): https://github.com/macel94/cloudnativeblazorpong

or do you expect a certain test to pass and to be added in the gh pipelines?

**Comment by macel94** [comment]
Hi

Seems like I was able to make it work following the official guides
![image](https://github.com/grafana/docker-otel-lgtm/assets/8000532/4d5e152d-5201-496c-ad0a-6ddf059071d0)
![image](https://github.com/grafana/docker-otel-lgtm/assets/8000532/3af306a3-e52d-4e6a-9b5d-7974b2f5a7b6)
![image](https://github.com/grafana/docker-otel-lgtm/assets/8000532/a3ebc45a-04a0-4fba-ab97-516eea4d29cf)

I'll try to explore how the oats tests you already implemented on the other examples work and get back to you

**Comment by macel94** [comment]
Solved, waiting for pr tba
