### ISSUE TITLE
Make the project Windows compatible

### ISSUE THREAD

**Issue by gian1200** [grafana/docker-otel-lgtm#63]
Currently, scripts are not runnable in native Windows (eg. Power Shell). It'd be nice to have a `.cmd` equivalent for each `.sh` file.

**Comment by zeitlinger** [comment]
Great idea - do you want to submit a PR?

**Comment by gian1200** [comment]
Sure, no problem. Although it might take a few days. I'm not an expert on Batch Script.

I only have 2 questions:
- Why is `dev` the default tag? Shouldn't it be `latest` (or empty)? I've seen it in `build-lgtm.sh` and `run-lgtm.sh`
- Can I also make the script compatible with `podman` (if found, keeping `docker` as default)? If yes, can I reuse the same PR or should I do a separate one?

**Comment by zeitlinger** [comment]
> Sure, no problem. Although it might take a few days. I'm not an expert on Batch Script.
> 
> I only have 2 questions:
> 
> * Why is `dev` the default tag? Shouldn't it be `latest` (or empty)? 

`latest` sounds good

>   - As a user I expected to only do `git clone` + `./run-lgtm.sh`, but I needed to modify it a bit to make it work

yes, should work out of the box

> * Can I also make the script compatible with `podman` (if found, keeping `docker` as fallback)? If yes, can I reuse the same PR or should I do a separate one?
>   - If podman found, use it; else if docker found, use it; else show message to install either podman or docker

yes, great idea - one or 2 prs, up to you :smile:
