### ISSUE TITLE
Build releases in CI

### ISSUE THREAD

**Issue by josegonzalez** [grafana/docker-otel-lgtm#66]
I was looking to see if this supported ARM64 natively, and it looks like the tags are pushed by a user manually as shown in the output [here](https://hub.docker.com/r/grafana/otel-lgtm/tags). Ideally this would be done in CI so I could more easily add arm64 support.

Is this something ya'll would take a PR for? It'll probably need permissions from a member of the Grafana org on Docker hub to set a secret on this repo to push.

**Comment by zeitlinger** [comment]
we have a new setup with google artifact registry, which is just not available for public repos yet.

**Comment by okolawole-ebsco** [comment]
@josegonzalez Support for ARM64 was added with this issue https://github.com/grafana/docker-otel-lgtm/issues/29. I guess what left is pushing the image to a public repo.

**Comment by josegonzalez** [comment]
Using the Google registry is cool but I think being able to attribute builds to CI would be excellent.

_Today_ artifacts are shipped to Docker Hub. If I made that work via CI, would such a PR be avoided by the Grafana Org?

**Comment by josegonzalez** [comment]
Note: you can change that to publish to any other target later. _Today_, the images are on docker hub, and mkaing those happen from CI is what I am trying to push towards.

**Comment by zeitlinger** [comment]
I don't mind an interim solution :smile:

**Comment by hannahchan** [comment]
Any update on this?

I just did a `docker pull grafana/otel-lgtm` on a Raspberry Pi only to find out the image was pull was for `amd64`. It would be nice if ARM images were available.

**Comment by zeitlinger** [comment]
version 0.7.2 supports arm - https://github.com/grafana/docker-otel-lgtm/blob/a5c3bec5202534b6b569ca4675eb9e66bf2cedfe/.github/workflows/release.yml#L26
