### ISSUE TITLE
Multi-arch image builds (ARM64 and AMD64)

### ISSUE THREAD

**Issue by ThomasVitale** [grafana/docker-otel-lgtm#70]
I can see that the Dockerfile in this repo has been updated to support multi-arch image builds in https://github.com/grafana/docker-otel-lgtm/issues/29.

It would be great if the process you currently use to build the image would trigger a multi-arch build, since right now the published images are AMD64 only. 

Any way we could help with that? I'm available to update the build process, should the suggestion of introducing a GH Actions pipeline be accepted (https://github.com/grafana/docker-otel-lgtm/issues/66). And achieve multi-arch builds, with also signatures and SLSA attestations.

**Comment by zeitlinger** [comment]
@fstab can you answer - as you're doing the build now

**Comment by okolawole-ebsco** [comment]
Looks like there was another release yesterday without arm64 images posted to docker hub.

**Comment by zeitlinger** [comment]
fixed in 0.7.2
