### ISSUE TITLE
Clean Data for Running Instance

### ISSUE THREAD

**Issue by okolawole-ebsco** [grafana/docker-otel-lgtm#72]
Hi! Is there a prescribe way to wipe the data for an existing instance of otel-lgtm without restarting? The docker container can be very expensive to start up. 

Thank you!

**Comment by zeitlinger** [comment]
This is actually beyond the scope of this docker container - which is intended for test purposes.

However, the backends (promentheus, loki, tempo) probably have api endpoints to do so)

**Comment by okolawole-ebsco** [comment]
Thank you!
