### ISSUE TITLE
Add a way to configure retention

### ISSUE THREAD

**Issue by josegonzalez** [grafana/docker-otel-lgtm#78]
Prometheus retention is configured via flag and not config, and thus there isn't a way right now to say "keep N weeks/months of data" without customizing the image. It would be great if we could somehow supply the retention (or even other flags) for use with prometheus.

**Comment by josegonzalez** [comment]
Happy to make a PR if folks have a good direction here. I don't really want to add knobs for _every_ possible flag, so whatever makes most sense to make this flexible works for me.

**Comment by zeitlinger** [comment]
the image is meant for testing - but I'll happily accept a PR

**Comment by zeitlinger** [comment]
If you want to have more advanced configs, you can do so by mounting config files like here:

https://github.com/grafana/docker-otel-lgtm/blob/2476e74e4980568d1003a526a8b2d887b7e8aff0/examples/java/json-logging-logback/k8s/lgtm.yaml
