### ISSUE TITLE
Add option to display logs of each components

### ISSUE THREAD

**Issue by bencehornak-gls** [grafana/docker-otel-lgtm#84]
Sometimes it is useful to see the logs of each components (Grafana, Loki, Prometheus, Tempo & OTel Collector), e.g. when changing a configuration file or an environment variable causes a component to crash.

At the moment the logs of the components are redirected to `/dev/null`, so there is no easy way to troubleshoot startup failures, like here for Grafana:
https://github.com/grafana/docker-otel-lgtm/blob/f346243b89600bcf11889eb18ded64cb2347f33c/docker/run-grafana.sh#L4

That said, I appreciate the simplicity of the bundle, so I understand that those logs are hidden by default.

So I would like to propose some environment variables, which would allow enabling logs of each component:
* `ENABLE_LOGS_ALL`
* `ENABLE_LOGS_GRAFANA`
* `ENABLE_LOGS_LOKI`
* `ENABLE_LOGS_PROMETHEUS`
* `ENABLE_LOGS_TEMPO`
* `ENABLE_LOGS_OTELCOL`

They would be all `false` by default. If the proposal is accepted, I'm happy to open a PR to implement.

**Comment by zeitlinger** [comment]
sounds great
